version: '3'
services:
  cache:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
  search:
    container_name: redis-search
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6378:6378
    volumes:
      - ./redis/search/redis.conf:/usr/local/etc/redis/redis.conf
  notification:
    container_name: redis-notification
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6377:6377
    volumes:
      - ./redis/notification/redis.conf:/usr/local/etc/redis/redis.conf
  app:
    depends_on:
      - cache
      - search
      - notification
    image: xiu0327/refrigerator
    ports:
      - 8080:8080
